# Generated by Django 5.1.1 on 2024-09-08 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_banner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='name',
        ),
    ]
