# Generated by Django 5.1.1 on 2024-09-09 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_brand_color_size_tag_product_additionalinfo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon'),
        ),
    ]
