# Generated by Django 5.1.1 on 2024-09-09 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(default=1, upload_to='service_icon/', verbose_name='Service icon'),
            preserve_default=False,
        ),
    ]
