# Generated by Django 5.1.1 on 2024-09-09 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_alter_service_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.FileField(upload_to='service_icon/', verbose_name='Service icon'),
        ),
    ]
