# Generated by Django 5.1.1 on 2024-09-11 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_alter_additionalinfo_product_alter_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images_color', to='products.color', verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes_color', to='products.color', verbose_name='Color'),
        ),
    ]
