# Generated by Django 5.1.1 on 2024-09-14 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_alter_productimage_color_alter_productsize_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizescolor', to='products.color', verbose_name='Color'),
        ),
    ]
