# Generated by Django 5.1.1 on 2024-09-29 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_alter_productsize_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=1, verbose_name='Rating'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.IntegerField(default=1, verbose_name='View count'),
            preserve_default=False,
        ),
    ]
