# Generated by Django 5.1.1 on 2024-09-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_rating_product_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=1, verbose_name='Discount'),
            preserve_default=False,
        ),
    ]
