# Generated by Django 5.1.1 on 2024-10-04 11:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_product_categorize'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitedTimeOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to='limited_time_offers_image/', verbose_name='Limited time offers image')),
                ('url', models.URLField(verbose_name='Limited time offers url')),
                ('end_date', models.DateField(verbose_name='Tugash sanasi')),
            ],
            options={
                'verbose_name': 'Limited time offers',
                'verbose_name_plural': 'Limited time offers',
            },
        ),
    ]
