# Generated by Django 5.1.1 on 2024-10-04 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_limitedtimeoffers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedtimeoffers',
            name='end_date',
            field=models.DateTimeField(verbose_name='Tugash sanasi'),
        ),
    ]
