# Generated by Django 5.1.1 on 2024-10-04 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_alter_limitedtimeoffers_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedtimeoffers',
            name='end_date',
            field=models.CharField(default=datetime.datetime(2025, 10, 4, 17, 18, 16, 395318), max_length=255, verbose_name='Tugash sanasi'),
        ),
    ]
