# Generated by Django 5.1.1 on 2024-10-04 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_alter_limitedtimeoffers_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedtimeoffers',
            name='end_date',
            field=models.CharField(default=datetime.datetime(7, 10, 4, 17, 34, 11, 27457), max_length=255, verbose_name='Tugash sanasi'),
        ),
    ]
