# Generated by Django 5.1.1 on 2024-10-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_alter_limitedtimeoffers_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitedtimeoffers',
            name='end_date',
            field=models.CharField(default='2025-10-10 00:00:00', max_length=255, verbose_name='Tugash sanasi'),
        ),
    ]
